### ISSUE TITLE
Meeting Agenda: May 12th 2022

### ISSUE THREAD

**Issue by lucacasonato** [wintercg/admin#18]
Time: Thursday, May 12 2022 1700-1745 UTC

### Agenda

_Please add items as needed._

1. Introductions (10m)
1. Review nominations for chairs, and start elections (15m)
1. Review logo (5m)
1. Set Matrix channel to public (5m)
1. Workstreams updates
    * Common APIs (5m)
    * Crypto Streams (5m)
    * Fetch subset (5m)

**Comment by blittle** [comment]
Meeting notes: https://docs.google.com/document/d/1J_B0Zv6Flq1WyNFeFRfvKNScKMIj-wJ6TCkK8sEyoao/edit#

**Next steps**
1. Go through the minimum common API and create issues as needed
2. Create issues on the browser vendors to identify who should be involved in crypto proposal - @lucacasonato 
3. Set up a separate meeting to specifically go through fetch spec
4. Create an issue outlining pa potential module format work stream - @maxshirshin
