### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by jasnell** [wintercg/admin#2]
As a W3C Community Group, the W3C has a standard Code of Conduct we should use.

Draft here: https://github.com/owpacg/bootstrap/blob/main/CODE_OF_CONDUCT.md

Use this issue to discuss.

**Comment by lucacasonato** [comment]
This was adopted last meeting. We are using this code of conduct: https://github.com/wintercg/admin/blob/main/CODE_OF_CONDUCT.md.

Files have been added to all repositories.
