### ISSUE TITLE
Greeting from ByteDance

### ISSUE THREAD

**Issue by XadillaX** [wintercg/admin#22]
Hi, I'm XadillaX from ByteDance. And now I and my teammates are making a Web-interoperable Runtime (V8 Worker) named *Hourai.js* in ByteDance. We've already joined the W3C WINTERCG. And how do we join this GitHub group?

Thanks.

**Comment by XadillaX** [comment]
#20

**Comment by lucacasonato** [comment]
Hello @XadillaX, and welcome to WinterCG! I have opened a PR with more information on joining at https://github.com/wintercg/admin/pull/24. You may find this useful.
