### ISSUE TITLE
Meeting Agenda: May 26th 2022

### ISSUE THREAD

**Issue by lucacasonato** [wintercg/admin#25]
Time: Thursday, May 26 2022 1700-1745 UTC

### Agenda

_Please add items as needed._

1. Introductions (5m)
1. Biweekly calls.. Google Meet or Zoom?
1. Workstreams updates
   1. Common APIs (5m)
   1. Crypto Streams (5m)
   1. Fetch subset (5m)

**Comment by Tseian** [comment]
Should the time of meeting be friendly a little more for people from China(asia) ? o(╥﹏╥)o.

**Comment by lucacasonato** [comment]
Notes in #26.

**Comment by lucacasonato** [comment]
> Should the time of meeting be friendly a little more for people from China(asia) ? o(╥﹏╥)o.

Please see #27 @Tseian

**Comment by Tseian** [comment]
> > Should the time of meeting be friendly a little more for people from China(asia) ? o(╥﹏╥)o.
> 
> Please see #27 @Tseian

Thank you.
