### ISSUE TITLE
Find a better meeting time

### ISSUE THREAD

**Issue by lucacasonato** [wintercg/admin#27]
The current bi-weekly meeting time is very hostile to folks in time zones in Asia (it's at 0100). It only really works well for US folks unfortunately.

This is a really hard problem because US east coast and China have pretty much no time overlap at all. I think to accommodate the most people, the best slots would be one of these:

| Slot | US west coast | US east coast | Europe | China |
| - | - | - | - | - |
| 1 | 0600 | 0900 | 1500 | 2100 |
| 2 | 0700 | 1000 | 1600 | 2200 |
| 3 | 0800 | 1100 | 1700 | 2300 |

These are all obviously not great for either US west coast, or China time zones, but I don't think we can do any better without introducing a rotating schedule.

WDYT?

**Comment by XadillaX** [comment]
Sorry, we missed the meeting yesterday because our calendar all misunderstood the time as 02:00 UTC+8🤣

I think we can use all of them. e.g. slot 1 this time, slot 2 next time and slot 3 next time after next time.

**Comment by exoticknight** [comment]
I vote for 3

**Comment by jasnell** [comment]
A rotating schedule works, I think. But let's have the folks joining from Asia weigh in before deciding.

**Comment by exoticknight** [comment]
any updates about this?

**Comment by Ethan-Arrowood** [comment]
React with 👍 to this comment for Option 3 😄

**Comment by ytxmobile98** [comment]
@lucacasonato @Ethan-Arrowood 

It comes to my attention that US DST will be ending in November.

How are we going to address this matter?

Do we still shift the time by one hour to match the US time zones, or use a fixed time zone (e.g. UTC or China standard time) as a reference for future meetings?

**Comment by ljharb** [comment]
I believe that a fixed timezone would make the meeting start at 7AM on the west coast, which is much harder to make than an 8AM start, but not impossible.

If we kept it at a fixed time in the US, so that it moved an hour later for those using fixed timezones, how much of a hardship would that be for those folks?

**Comment by penzn** [comment]
Being on US west cost I'd prefer option 2 or 3 for fixed meeting.

In my experience rotating schedule or is probably the easiest way to resolve scheduling, though it would create a different headache with agenda. Trying to find meeting time for all three continents is always the problem of midnight for one side vs 6 AM for the other, as Europe, US, and Asia are nearly equal number of hours apart from one another.

For rotating meeting with two slots it might be possible to group US East + Europe and US West + Asia.

**Comment by lucacasonato** [comment]
The new meeting schedule is a 3-way rotation, rotating between the following slots:

| UTC | EU | US West | US East | China |
| -- | -- | -- | -- | -- |
| Thu 0:00 | Thu 1:00 | Wed 16:00 | Wed 19:00 | Thu 8:00 |
| Thu 8:00 | Thu 9:00 | Thu 0:00 | Thu 3:00 | Thu 16:00 |
| Thu 16:00 | Thu 17:00 | Thu 8:00 | Thu 11:00 | Fri 0:00 |

@jasnell will be updating the shared Google Calendar with these times.
