### ISSUE TITLE
IP Governance Draft

### ISSUE THREAD

**Issue by jasnell** [wintercg/admin#3]
We'll need a standard `LICENSE` file for all repositories. Community Groups are expected to use the W3C Software and Document License:

```
Materials in this Repository are licensed by Contributors
under the
[W3C Software and Document License](http://www.w3.org/Consortium/Legal/2015/copyright-software-and-document).

Contributions to Specifications are made under the
[W3C CLA](https://www.w3.org/community/about/agreements/cla/).

Contributions to Test Suites are made under the
[W3C 3-clause BSD License](https://www.w3.org/Consortium/Legal/2008/03-bsd-license.html)
```

Use this issue for discussion.

**Comment by lucacasonato** [comment]
We are using the 'W3C Software and Document License' for all work products, as is mandated by W3C for CGs. This has been recorded in all repos in the "CONTRIBUTING.md" file, and is enforced through the IPR bot (#13).
