### ISSUE TITLE
Meeting Agenda: 2022-06-30

### ISSUE THREAD

**Issue by lucacasonato** [wintercg/admin#30]
Time: Thursday, June 30 2022 1700-1745 UTC

### Agenda

_Please add items as needed._

1. Introductions (5m)
1. Fetch discussions (40m)
   1. What is the current common subset of fetch?
   1. CORS
   1. Cookie handling
   1. Request body streaming - full or half duplex?
   1. Meta information on Request/Response instances

**Comment by maxshirshin** [comment]
Meta information on Request/Response instances

**Comment by Tseian** [comment]
https://fetch.spec.whatwg.org/

**Comment by lucacasonato** [comment]
Who did the meeting notes for this one? @jasnell did you do it?
