### ISSUE TITLE
Meeting agenda: 25-08-2022

### ISSUE THREAD

**Issue by lucacasonato** [wintercg/admin#35]
Time: Thursday, August 25 2022 1700-1745 UTC

### Agenda

_Please add items as needed._

1. Fetch compatibility (30m)
   1. https://github.com/wintercg/fetch 
1. Workstreams updates
   1. Common APIs (5m)
      1. OffscreenCanvas https://github.com/wintercg/proposal-common-minimum-api/issues/26
   1. Crypto streams (5m)
      1. Update on spec positions from WebKit?
   1. Environment data (5m) 
   1. Performance (5m)

**Comment by phoddie** [comment]
The call is now?! I signed up for WinterCG via W3C. How can I access the information to join the call? Thank you.

**Comment by lucacasonato** [comment]
@phoddie Can you join Matrix: https://matrix.to/#/#wintercg:matrix.org ? I'll send you a meet invite.

**Comment by phoddie** [comment]
Thanks. Yes, I am now on Matrix. I see the video call link, and am waiting to be allowed to join.
