### ISSUE TITLE
Meeting Link

### ISSUE THREAD

**Issue by legendecas** [wintercg/admin#37]
We've got several times that people are sitting in the waiting room and frustrated to find that they are not invited. Owners of the meeting may not be present at the meeting so those folks can not join the meeting and attendees can do nothing to help people joining the meeting.

Can we create a meeting link that is open to anyone without an invitation?

**Comment by exoticknight** [comment]
or a meet that requires password to join？

**Comment by frehner** [comment]
Would be very cool to have a spectator link that's open to anyone but doesn't have the ability to speak or something. For those of us interested in listening in but not part of the group.

**Comment by jasnell** [comment]
I'm going to set up a zoom link instead of the google chat to make the meetings easier. I'll get that posted later on today.

**Comment by legendecas** [comment]
The link has been updated. Closing. Thanks!
