### ISSUE TITLE
Recording the meetings

### ISSUE THREAD

**Issue by ytxmobile98** [wintercg/admin#38]
Some of my colleagues at ByteDance are kindly requesting if the meetings could be recorded as video for reviewing afterwards (not just meeting notes). Basically they need to take care of children after work, and the meeting time (for China) is a major inhibitor for them to do that as well as attend our meetings on a regular basis.

More than this, I have noticed that we often have folks unable to attend this meeting due to personal circumstances. This puts them in trouble with keeping updated with our community's progress and continuously pushing our discussions forward.

**So ideally we would like to see if we may have the meetings recorded. With the meetings recorded, everyone can have a chance to review these recordings in the middle of the weeks, and use them as references for preparing future meetings to progress our prior discussions.**

I would like to see if either option is viable for @jasnell :
1. Record the meeting and makes it available for distributing to our fellow members.
2. Open up the permission in Zoom for this meeting, so that individual members can opt for recording the meeting by themselves if they want.

Thanks.

**Comment by ytxmobile98** [comment]
Some of my colleagues at ByteDance are kindly requesting if the meetings could be recorded as video for reviewing afterwards (not just meeting notes). Basically they need to take care of children after work, and the meeting time (for China) is a major inhibitor for them to do that as well as attend our meetings on a regular basis.

So ideally we would like to see if we may have the meetings recorded, so that everyone can have a chance to review these recordings and use them as references for preparing future meetings to progress our prior discussions.

I would like to see if either option is viable for @jasnell :
1. Record the meeting and makes it available for distributing to our fellow members.
2. Open up the permission in Zoom for this meeting, so that individual members can opt for recording the meeting by themselves if they want.

Thanks.

**Comment by jasnell** [comment]
We have recording enabled for the zoom calls now! I've been looking at options for automating sharing of the links but none of the options are great. I think maybe perhaps we can set a live stream to youtube which may be easier.
