### ISSUE TITLE
[Meeting] 2022-11-17 08:00 Pacific Time

### ISSUE THREAD

**Issue by Ethan-Arrowood** [wintercg/admin#40]
## Agenda

- Fetch Spec fork initial modifications : https://github.com/wintercg/fetch-standard/pull/1
- runtime keys spec : https://github.com/wintercg/runtime-keys/pull/2

**Comment by ytxmobile98** [comment]
Does anyone have interests in TypeScript configuration?

https://github.com/wintercg/proposal-common-minimum-api/issues/31

**Comment by Ethan-Arrowood** [comment]
Great idea @ytxmobile98 - lets discuss this at the meeting

**Comment by Ethan-Arrowood** [comment]
Meeting Notes:

- Fetch
  - Luca and Ethan will work on merging initial PR and consolidating the wintercg/fetch repo into wintercg/fetch-standard before then renaming the later to the former.
  - Next meeting goal: make progress on fetch issues - specifically set cookie maybe
- Runtime Keys
  - Waiting on Vercel 
  - Ethan needs to add some more clarifying info about what the proposal is for and participation criteria
- Typescript definition file
  - Bloomberg to reach out to TypeScript core about collaborating
- https://w3c.github.io/edge-computing-web-exploration/
  - Folks are encouraged to review and reach out if interested in participating

**Comment by ytxmobile98** [comment]
@jasnell May you provide the link for the recorded meeting please? Thank you.

**Comment by jasnell** [comment]
Meeting recording: https://us06web.zoom.us/rec/share/3IxPBJobzV0sWtEIdlV2KBbNZWK-9FsdP0Ey_LMd0Jj-yYsiZ2fqHPL3PckewWVw.tuyt8oA0DBZvQ_BS 
Passcode: .@YRpB6j
