### ISSUE TITLE
Co-chair self-nominations

### ISSUE THREAD

**Issue by CanadaHonk** [wintercg/admin#68]
Let's use this issue as a thread for people to nominate themselves to become co-chair with a potential new selection.

As per [the chair selection process in the charter](https://github.com/wintercg/admin/blob/90850866c2fc30671b7cb82ab0e033ad3f133c55/charter.md#chair-selection), participants have 14 days to announce their candidacies for Chair (here) if an election is called.

**Comment by jasnell** [comment]
I've found myself with less and less time these days to focus on Chair responsibilities so I would be open to stepping back and allowing a new selection process to replace myself as the chair. I think it would be great if we gave it a week or two for folks to self-nominate if they are interested then from there figure out a selection vote if we have multiple folks interested.

/cc @lucacasonato

**Comment by CanadaHonk** [comment]
I would like to nominate myself to become a co-chair of WinterCG. As of today, I am officially affiliated with and representing [Porffor](https://porffor.dev) (both in this issue and on w3.org).

I am nominating myself as WinterCG has now become related to my full-time work, and I have been very active in the past. With this new found time I can become active again and would like to use some of that time helping to chair the CG. My hope in becoming a co-chair is to make things even more active and also add some representation for non-web-APIs and smaller orgs/engines. Thank you!

**Comment by lino-levan** [comment]
I believe this was resolved in #67. Congratulations @CanadaHonk!
