### ISSUE TITLE
Dedicated standardization meeting 2024-08-29

### ISSUE THREAD

**Issue by CanadaHonk** [wintercg/admin#70]
As discussed on Matrix, let's have a dedicated supplemental meeting next week at the typical WinterCG meeting time (Thursday, 14:30 UTC) just to talk about the current standardization situation and where to go from here.

**Comment by littledan** [comment]
Background on the current standardization situation: https://github.com/wintercg/admin/issues/58#issuecomment-2303058009

**Comment by littledan** [comment]
To be clear, we're talking about August 29th, right?

**Comment by jasnell** [comment]
Yes, August 29th

**Comment by CanadaHonk** [comment]
@jasnell Could you please add this to the WinterCG calendar and set up a call if possible?

**Comment by littledan** [comment]
This meeting is going ahead. See you on Thursday, everyone!

**Comment by CanadaHonk** [comment]
Notes:
- Dan: Intellectual property concerns blocked by Google and Mozilla for combined W3C CG and ECMA TC. Some people in W3C feel strongly that only a WG should be used for details/specs. Now that the minimum common API is becoming more agreed upon it should likely be moved to a WG. See also: CLI API, upstreaming fetch changes (we don’t want to maintain our own fetch separately and instead work with the existing WG). Having someone else standardize what happens in the CG has concerns and wouldn’t work well. A TC or WG would be scoped only to the minimum common API, not the entirety of WinterCG. 1. We need to choose if we do everything in W3C or ECMA. I’m happy with both but we cannot span both. 2. As we are developing a high-level of standards, it should not happen in WinterCG as it that is not what CGs are for; we should do it either in a W3C WG or ECMA TC. A CG-like thing for ECMA could be possible. W3C and ECMA have invited expert programs. For W3C the strictness of the policy depends on the WG, and for ECMA too but I have had a positive experience with it. Whether we use a WG or TC we should ensure inclusion is possible. Companies should still pay but we’ll have to see on a case-by-case basis (?)
- Samina: You mentioned either W3C or ECMA, and there’s a difference with a W3C CG and WG. Is there a third option where a CG -> WG is lengthy/difficult; could the CG do its work in ECMA but with a clear MoU (Memorandum of Understanding).
- Dan: If ECMA and W3C make an agreement like WHATWG and W3C have then it could be possible but I don’t think a new separate solution is necessary.
- Luca: Given the options, I would like to pursue the ECMA path. I think more members of this group are part of ECMA and not part of W3C; like Deno, Cloudflare (in the process of becoming an ECMA member), Vercel. Other members of this group are also invited members in other TCs. I think meetings should be open for anyone to join and see how an invited expert process works there. I would like to ensure a public-facing calendar continues for anyone to join. I would also be okay for a W3C path but I think it involves more hurdles due to things mentioned previously.
- Dan: How non-negotiable is this 0 process for joining a meeting? We should enforce people have signed forms before joining a meeting.
- James: The original intent was to be as open as we possibly can be for meetings, and keep it as low-process as possible. If moving forward we get more into the formal process of defining a standard then we should become more serious and defining an IPR. It’s a different process. For meetings talking about the standards, signing should be required. We could divide meetings into open discussion and then specific standards talk.
- Luca: When you go on the W3C WinterCG page, you can join the CG and sign the IPR policy. I think everyone attending these calls have signed it.
- Dan: Some members definitely haven’t signed due to restrictions with them having to join as their employer.
- Ethan: +1
- Dan: Your employer is supposed to sign to help IPR as the employer could claim they own the IPR as it was used during work hours (?) or claim they own the license to work done on any standards.
- Aki: It’s important that people sign the (CG?) CLA before they contribute anything which is standardized. An employer could claim years later they own a patent and force trouble requiring a lot of work later on. It is very important that you have your employer’s permission most of the time (depending on contracts etc). W3C members (companies) can choose not to participate in a CG, then they are not bound by IPR agreements until they join the group. The CLA is reasonably short and not onerous (?) as it is designed for proposing standards to WGs which then make the details from there. WGs have specific charters and people have mixed opinions on how easy it is to have one chartered, it seems to depend. ECMA’s IP policies are similar to W3C’s but what was previously proposed (?) would make companies have to license any potential patents to two different standards bodies which lawyers hate. There is an opt-out period in the CG CLA to avoid contributions you could avoid having your IP in. Most software companies just have patents to avoid patent trolls. In theory it is sub-licensable and licensed in derivative works, so W3C could sub-license ECMA and ECMA published specifications could be derivative works (?). Getting participants to sign the CLA before joining any meeting protects everyone so 5 years down the line we don’t have to rewrite things from scratch due to some patent claim. People are only licensing their own patents on their own contributions so it should hopefully be a low bar. There could be a possible way forward for a W3C CG and a ECMA TC but it would take a lot of time and lawyers and effort, so if it makes more sense to move everything to ECMA or try to charter a WG, we can do that instead.
- James: I don’t know if we have enough time to try to coordinate a MoU between the two organizations. Leaning towards ECMA and taking the hit to increase the process required. If we go that route, I think we should model things off of TC39 for engaging the community and non-members on individual proposals. We should actively do that while balancing being closed (short-term) for IPR reasons. If it is ECMA or W3C, I would prefer we go to ECMA entirely.
- Yoav: From the W3C side, I think the main thing to consider is if there is already a critical mass of participants as everyone not ECMA members would need invited expert status. Getting invited expert status for ex-W3C members is very hard for W3C, otherwise we have had a good track record of getting IEs for the web performance group. Ensuring browser vendor folks are outnumbered by community members in meetings has worked for it too. The MoU method sounds monumental. The discussed scope sounds reasonable to get chartered. AC members can sometimes get annoyed with a new charter but I wouldn’t expect any objections for a WG. The web performance group also has observers. An issue (comment) is not a contribution, a PR is a contribution. If a non-member is getting into the weeds, it is my role (as a chair) to stop them and get them to join. (?) There is a fuzzy line to draw there. That is a question for how chairs want to run the meeting.
- Dan: I would like to run a potential WG similar to the web performance WG. Is there a risk of pushback from W3C staff or someone worried about IP due to having observers/invited experts?
- Yoav: Most pushback is from W3C business people wanting to see invited experts converted. If an invited expert is not actively contributed, there is some pressure to remove them but it works fine for active invited experts. There is some push to make a minimal amount of invited experts to help fund W3C and not sure how ECMA is with that.
- Samina: I think ECMA has a good invited expert policy, but invited experts are not IEs for life; if they are part of an organization they should eventually join (?). I think it is important for the decision for ECMA vs W3C to be a CG decision. I don’t think an MoU would be unreachable and engage legal staff to do it effectively with W3C. We would like the CG or TC55/etc to work without worrying about IPR.
- Dan: RE: not wanting someone to be invited experts for life; we want organizations to be members and can have them be invited experts for some months and then join. Some people are not associated with an organization so can just be invited experts, eg Babel. But we also want to trim inactive invited experts. There is no real time limit and is mostly handled on a case-by-case basis.
- Samina: +1
- Luca: Filling the form for W3C (?) is just checking some boxes on the website. If IEs need a time limit, like not joining 5 meetings in a row results in off-boarding, that does not seem unreasonable as long as you can rejoin later. As long as it is easy to become an IE it seems acceptable to me to remove inactive IEs.
- James: If I am an IE and I become inactive, I would not get removed right away, there would be a grace period.
- Luca: I think the important part is that becoming an IE takes 3 weeks, it should be filling a form and then within the week you can join the meeting.
- Dan: You cannot ask to be an IE for TC39, someone inside of TC39 has to nominate you.
- James: I think there should be a review process for IEs, at very least run by the chairs. The original idea as a coordination group, we have to have at least that kind of guard if we are actually producing standards.
- Andreu: (experience with contributing to CSSWG and WHATWG)
- Dan: Would you say CSSWG doesn’t face any barriers to contribution based on W3C structures?
- Andreu: Probably. (?)
- Yoav: I think W3C would be more fitting as most common minimum API features are in W3C/WHATWG, it feels more natural/smoother.
- Dan: We could still communicate.
- Yoav: I still think it would go smoother if it is in W3C.
- Dan: That is true, there would have to be process improvements working with ECMA.
- Owen: Fetch is part of WHATWG, so does it matter if we bring an idea from there to here?
- Dan: W3C has a role for WHATWG IP things, among this group we would still go out to W3C and propose things there, which we have already been doing. I think doing it in a CG would be the coordination point for that, but it could be either one. It involves spanning CG values regardless anyway.

**Comment by littledan** [comment]
Following the notes that Oliver posted above, all WinterCG participants either voiced a preference for proceeding entirely in Ecma or were neutral on the alternatives.

The next steps for WinterCG, to be led by Dan, Oliver and James, are to develop a more concrete plan to charter both a TC in Ecma to focus on the minimum-common-API, as well as to work with Ecma on a new process for establishing a CG-like structure for the broader scope of other APIs and coordinating with other standards bodies on upstream changes. We will continue this discussion in the following WinterCG meeting in one week before adopting any firm conclusion for the group.
